// <auto-generated />
namespace SIMrelease.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SIM3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SIM3));
        
        string IMigrationMetadata.Id
        {
            get { return "202310020910400_SIM3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
